version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        expose:
            - "9000"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql

    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        depends_on:
            - web

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
